#spring.application.name=group76_part1
#spring.datasource.url=jdbc:mysql://localhost:3306/safe_dispatch_db
#spring.datasource.username=root
#spring.datasource.password=Evovyog@uni42
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keys.jks
server.ssl.key-store-password=password
server.ssl.key-store-type=JKS
server.ssl.key-alias=KaranSingh
#


# --- Server ---
server.port=8443

# --- MySQL Database ---
spring.datasource.url=jdbc:mysql://localhost:3306/safe_dispatch_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true